using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LidToggleButton : MonoBehaviour
{
    public List<GameObject> colliderList = new List<GameObject>();
    public void OnTriggerEnter(Collider collider)
    {
        if (!colliderList.Contains(collider.gameObject))
        {
            colliderList.Add(collider.gameObject);
        }
        
        
    }

    public void OnTriggerExit(Collider collider)
    {
        if (colliderList.Contains(collider.gameObject))
        {
            colliderList.Remove(collider.gameObject);
        }
    }

    public List<GameObject> AllGameObject()
    {
        return colliderList;
    }
}
